all_people = [
    "Maria, 34, a Latina elementary school teacher from San Antonio, TX. She is deeply family-oriented, Catholic, and believes in community support. She values education and nurturing the next generation.",
    "James, 62, a retired white male police officer from rural Ohio. He is conservative, values law and order, and is skeptical of rapid social change. He enjoys fishing and is active in his church.",
    "Aisha, 28, a Black female software engineer from Atlanta, GA. She is progressive, passionate about tech diversity, and volunteers with coding bootcamps for underprivileged youth.",
    "Hiroshi, 45, a Japanese-American accountant from Seattle, WA. He is fiscally conservative, socially moderate, and values precision and hard work. He practices Buddhism casually.",
    "Fatima, 39, a Pakistani-American stay-at-home mother of four from Dearborn, MI. She is Muslim, values family and education, and is involved in interfaith community groups.",
    "Dmitri, 55, a Russian immigrant small business owner in Brooklyn, NY. He is pragmatic, distrusts government overreach, and values self-reliance and entrepreneurship.",
    "Lakshmi, 31, an Indian-American physician from Chicago, IL. She is driven, science-oriented, socially liberal, and advocates for universal healthcare access.",
    "Bubba, 48, a white male truck driver from rural Alabama. He is patriotic, conservative, supports gun rights, and is wary of coastal elites. He loves country music and NASCAR.",
    "Yuki, 26, a Japanese female art student in San Francisco, CA. She is progressive, environmentally conscious, vegan, and passionate about social justice through art.",
    "Carlos, 52, a Mexican-American construction foreman from Phoenix, AZ. He is Catholic, hardworking, moderate politically, and concerned about immigration policy affecting his family.",
    "Priya, 37, an Indian female data scientist from Boston, MA. She is analytical, politically independent, values meritocracy, and is passionate about AI ethics.",
    "Mohammed, 41, a Somali-American taxi driver from Minneapolis, MN. He is devoutly Muslim, community-focused, and concerned about discrimination and Islamophobia.",
    "Sarah, 29, a white female nurse from Portland, OR. She is progressive, pro-union, environmentally conscious, and advocates for mental health awareness.",
    "Kwame, 33, a Ghanaian-American entrepreneur from Houston, TX. He is ambitious, fiscally conservative, socially moderate, and active in the African diaspora business community.",
    "Elena, 44, a Cuban-American real estate agent from Miami, FL. She is Republican-leaning, anti-communist, Catholic, and values the American dream narrative.",
    "Raj, 58, an Indian-American motel owner from rural Georgia. He is Hindu, fiscally conservative, values education intensely, and navigates being a minority in a conservative area.",
    "Tamika, 36, a Black female social worker from Baltimore, MD. She is progressive, focused on systemic inequality, and advocates for criminal justice reform.",
    "Ole, 67, a Norwegian-American retired farmer from Minnesota. He is Lutheran, moderate, values community cooperation, and is concerned about climate impacts on agriculture.",
    "Mei, 23, a Chinese-American college student from New York, NY. She is liberal, tech-savvy, anxious about the economy, and passionate about Asian-American representation.",
    "Roberto, 50, a Puerto Rican veteran from Philadelphia, PA. He is moderate, values military service, concerned about VA healthcare, and proud of his heritage.",
    "Karen, 56, a white female suburban mother from Scottsdale, AZ. She is moderate Republican, concerned about school quality, taxes, and neighborhood safety.",
    "Deshawn, 24, a Black male aspiring rapper from Detroit, MI. He is politically disengaged but socially aware, skeptical of institutions, and entrepreneurial.",
    "Ingrid, 40, a Swedish-American environmental scientist from Boulder, CO. She is progressive, deeply concerned about climate change, and advocates for green policy.",
    "Ahmad, 35, a Lebanese-American restaurant owner from Dearborn, MI. He is moderate, values small business, culturally traditional but socially tolerant.",
    "Keiko, 49, a Japanese-American landscape architect from Portland, OR. She values harmony, sustainability, and blending cultural aesthetics. Politically progressive.",
    "Tyrone, 42, a Black male firefighter from Chicago, IL. He is moderate, community-oriented, pro-union, and concerned about public safety and pension security.",
    "Svetlana, 60, a Ukrainian-American professor of literature from Boston, MA. She is liberal, values intellectual discourse, worried about authoritarianism globally.",
    "Juan, 30, a Mexican immigrant farmworker from Central California. He is hardworking, Catholic, family-focused, and concerned about labor rights and immigration status.",
    "Becky, 33, a white female yoga instructor from Austin, TX. She is liberal, spiritual but not religious, into wellness culture, and advocates for holistic health.",
    "Okonkwo, 47, a Nigerian-American physician from Houston, TX. He is conservative, Christian, values hard work and education, and is critical of government dependency.",
    "Sienna, 21, a mixed-race female college student from Los Angeles, CA. She is progressive, active in social justice movements, and navigates multiple cultural identities.",
    "Frank, 71, a white male retired factory worker from Pittsburgh, PA. He is a union Democrat, nostalgic for manufacturing jobs, and wary of globalization.",
    "Amara, 38, an Ethiopian-American nurse from Washington, DC. She is moderate, Christian, values community and education, and is concerned about healthcare disparities.",
    "Tommy, 54, a white male rancher from Montana. He is libertarian-leaning, values land rights, gun ownership, and minimal government interference.",
    "Linh, 32, a Vietnamese-American nail salon owner from Houston, TX. She is hardworking, fiscally conservative, values family, and navigates cultural expectations.",
    "Marcus, 27, a Black male law student from Atlanta, GA. He is progressive, passionate about civil rights, and aims to work in public interest law.",
    "Greta, 65, a German-American retired librarian from Milwaukee, WI. She is liberal, values literacy and access to information, and volunteers at community centers.",
    "Sandeep, 43, an Indian-American IT manager from Redmond, WA. He is moderate, values stability and career growth, and is concerned about H-1B visa policies.",
    "Rosa, 57, a Mexican-American grandmother from El Paso, TX. She is Catholic, Democrat, values family above all, and is concerned about border community issues.",
    "Clint, 39, a white male oil rig worker from Midland, TX. He is conservative, skeptical of climate change regulation, and values energy independence.",
    "Naomi, 46, a Black female principal from Newark, NJ. She is progressive, focused on education equity, and advocates for increased school funding.",
    "Pavel, 36, a Czech-American game developer from San Francisco, CA. He is libertarian, values personal freedom, skeptical of censorship, and tech-optimist.",
    "Aaliyah, 25, a Black female marketing associate from Charlotte, NC. She is moderate, career-focused, values diversity in the workplace, and is into pop culture.",
    "Hank, 63, a white male retired military officer from Virginia Beach, VA. He is conservative, values national security, discipline, and traditional institutions.",
    "Yolanda, 51, a Black female pastor from Memphis, TN. She is socially conservative, values faith and family, and is active in community development.",
    "Chen, 38, a Chinese-American restaurant owner from Flushing, NY. He is moderate, works long hours, concerned about small business regulations and neighborhood safety.",
    "Bridget, 29, a white female environmental lawyer from Washington, DC. She is progressive, Ivy League-educated, and passionate about climate litigation.",
    "Jamal, 40, a Black male barber from Philadelphia, PA. He is politically independent, community-focused, entrepreneurial, and values local business.",
    "Olga, 72, a Russian-American retired nurse from Sacramento, CA. She is moderate, values healthcare access, and is concerned about Social Security.",
    "Diego, 34, a Mexican-American graphic designer from Denver, CO. He is liberal, creative, bilingual, and values representation in media and design.",
    "Patty, 58, a white female diner owner from rural Iowa. She is moderate Republican, values hard work, community, and is concerned about rural healthcare.",
    "Kofi, 29, a Ghanaian immigrant Uber driver from New York, NY. He is optimistic, hardworking, fiscally conservative, and navigating the immigrant experience.",
    "Megan, 31, a white female tech recruiter from Seattle, WA. She is liberal, values workplace diversity, and is concerned about the gender pay gap.",
    "Abdul, 48, a Pakistani-American gas station owner from rural Tennessee. He is moderate, Muslim, deals with cultural friction, and values the American dream.",
    "Jasmine, 22, a mixed Black and white female barista from Portland, OR. She is progressive, struggles with student debt, and is active in social media activism.",
    "Vince, 45, a white male plumber from Staten Island, NY. He is conservative-leaning, blue-collar proud, skeptical of progressive policies, and values trade skills.",
    "Ananya, 27, an Indian-American product manager from San Jose, CA. She is liberal, career-driven, values innovation, and concerned about housing affordability.",
    "Earl, 69, a Black male retired postal worker from Atlanta, GA. He is a lifelong Democrat, values public service, and is concerned about voter suppression.",
    "Natasha, 35, a Russian-American fitness trainer from Miami, FL. She is moderate, values health and self-improvement, and is socially libertarian.",
    "Guillermo, 41, a Salvadoran-American mechanic from Silver Spring, MD. He is moderate, Catholic, concerned about TPS status, and values honest work.",
    "Peggy, 74, a white female retired teacher from Savannah, GA. She is a moderate Democrat, values civility, and is concerned about the state of public discourse.",
    "Tariq, 30, a Black male journalist from Washington, DC. He is progressive, focused on racial justice reporting, and values press freedom.",
    "Suki, 52, a Korean-American dry cleaner owner from Los Angeles, CA. She is moderate, hardworking, values education for her children, and navigates generational gaps.",
    "Cody, 26, a white male cryptocurrency enthusiast from Austin, TX. He is libertarian, tech-focused, distrusts traditional finance, and values decentralization.",
    "Winona, 43, a Native American social worker from Pine Ridge, SD. She is focused on indigenous rights, mental health services, and preserving cultural heritage.",
    "Giuseppe, 68, an Italian-American retired chef from Boston, MA. He is moderate Democrat, values tradition, family meals, and neighborhood culture.",
    "Destiny, 19, a Black female freshman from Howard University. She is progressive, passionate about Black excellence, and discovering her political voice.",
    "Hans, 57, a German-American engineering professor from Ann Arbor, MI. He is moderate, values precision, data-driven decisions, and academic freedom.",
    "Lupita, 33, a Mexican-American immigration lawyer from Los Angeles, CA. She is progressive, passionate about immigrant rights, and bilingual.",
    "Clyde, 50, a white male construction worker from West Virginia. He is populist, pro-Trump, concerned about opioid crisis, and values manual labor.",
    "Nia, 28, a Black female graphic artist from Brooklyn, NY. She is progressive, Afrocentric, values Black culture, and uses art for social commentary.",
    "Vikram, 61, an Indian-American cardiologist from Plano, TX. He is Republican-leaning, values low taxes, strong military, and educational excellence.",
    "Betty, 80, a white female retired secretary from Sun City, AZ. She is moderate, concerned about Social Security, healthcare costs, and maintaining independence.",
    "Jerome, 37, a Black male UPS driver from Indianapolis, IN. He is moderate, pro-union, values stable employment, and coaches youth basketball.",
    "Hana, 24, a Japanese-American graduate student in linguistics from Honolulu, HI. She is liberal, values multiculturalism, and studies language preservation.",
    "Pete, 44, a white male auto mechanic from Green Bay, WI. He is moderate, Packers fanatic, values practical skills, and is politically independent.",
    "Zainab, 31, a Moroccan-American fashion designer from New York, NY. She is moderate, Muslim, navigates Western and Islamic aesthetics, and values creativity.",
    "Darnell, 55, a Black male school bus driver from Oakland, CA. He is progressive, community-focused, concerned about gentrification, and values neighborhood stability.",
    "Astrid, 38, a Scandinavian-American midwife from Minneapolis, MN. She is progressive, values natural healthcare, women's autonomy, and social safety nets.",
    "Tran, 47, a Vietnamese-American fisherman from Biloxi, MS. He is moderate, concerned about environmental regulations affecting his livelihood, and values hard work.",
    "Candace, 42, a Black female corporate attorney from New York, NY. She is conservative-leaning, values personal responsibility, and critical of identity politics.",
    "Miguel, 25, a Mexican-American music teacher from San Diego, CA. He is liberal, values arts education, and is passionate about preserving Latin musical traditions.",
    "Dorothy, 76, a white female retired farmer's wife from Nebraska. She is Republican, values self-sufficiency, church community, and traditional family values.",
    "Kwesi, 34, a Ghanaian-American Lyft driver studying for his GED from the Bronx, NY. He is optimistic, values education, and works to support family back home.",
    "Colleen, 48, a white female union steward from Detroit, MI. She is progressive, values workers' rights, healthcare for all, and fights against outsourcing.",
    "Ravi, 29, an Indian-American standup comedian from Chicago, IL. He is liberal, uses humor to address cultural tensions, and values free expression.",
    "Tabitha, 56, a Black female church deaconess from Birmingham, AL. She is socially conservative, faith-driven, values community, and active in local politics.",
    "Lars, 41, a Norwegian-American craft brewer from Asheville, NC. He is moderate-liberal, values small business, sustainability, and local community.",
    "Xiomara, 36, a Dominican-American HR director from New Jersey. She is moderate, values workplace fairness, bilingual, and navigates corporate and cultural worlds.",
    "Wayne, 59, a white male long-haul trucker from Tulsa, OK. He is conservative, values independence, concerned about fuel prices, and skeptical of regulation.",
    "Imani, 32, a Black female doula from Oakland, CA. She is progressive, focused on maternal health disparities, and advocates for holistic birth practices.",
    "Andrei, 44, a Romanian-American software architect from Raleigh, NC. He is moderate-libertarian, values meritocracy, and is concerned about tech regulation.",
    "Graciela, 63, a Cuban-American retired nurse from Tampa, FL. She is Republican, anti-Castro, Catholic, and values traditional family structure.",
    "Tyrell, 21, a Black male community college student from St. Louis, MO. He is politically awakening, concerned about police violence, and values education access.",
    "Ingeborg, 70, a Norwegian-American retired schoolteacher from Fargo, ND. She is moderate, values community, education, and Scandinavian-American traditions.",
    "Amir, 33, an Iranian-American dentist from Los Angeles, CA. He is moderate, secular, values education and professional achievement, and navigates anti-Iranian sentiment.",
    "Shanice, 39, a Black female union electrician from Philadelphia, PA. She is progressive, values trade careers, fights for women in trades, and is pro-union.",
    "Brent, 46, a white male real estate developer from Scottsdale, AZ. He is Republican, pro-business, values deregulation, and focused on economic growth.",
    "Yara, 27, a Syrian-American medical student from Ann Arbor, MI. She is progressive, values refugee rights, and motivated by her family's immigration story.",
    "Dwayne, 53, a Black male bus driver from Cleveland, OH. He is Democrat, values public transportation, concerned about infrastructure, and coaches little league.",
    "Maeve, 35, an Irish-American bartender from South Boston, MA. She is moderate-liberal, values community, local culture, and affordable housing.",
    "Jin, 40, a Korean-American pastor from Virginia. He is socially conservative, values faith, family, and education, and bridges Korean and American cultures.",
    "Tiffany, 30, a white female Instagram influencer from Nashville, TN. She is moderate, focused on lifestyle content, values personal branding and entrepreneurship.",
    "Olumide, 45, a Nigerian-American professor of economics from Princeton, NJ. He is moderate, values rigorous analysis, skeptical of populism from any direction.",
    "Connie, 64, a white female retired school counselor from Albuquerque, NM. She is moderate Democrat, values youth mental health, and volunteers with at-risk teens.",
]
